In [1]:
import numpy as np


In [2]:
arr = np.array([10, 20, 30, 40, 50])


In [3]:
print("Array:", arr)

Array: [10 20 30 40 50]


In [4]:
print("Shape:", arr.shape)

Shape: (5,)


In [5]:
print("Size:", arr.size)

Size: 5


In [6]:
print("Dimension:", arr.ndim)

Dimension: 1


In [7]:
print("Data Type:", arr.dtype)

Data Type: int64


In [8]:
print("Max:", np.max(arr))

Max: 50


In [9]:
print("Min:", np.min(arr))

Min: 10


In [11]:
print("Sum:", np.sum(arr))

Sum: 150


In [12]:
print("Sorted Array:", np.sort(arr))

Sorted Array: [10 20 30 40 50]


In [15]:
arr2 = np.array([[1, 2],[3, 4]])

In [14]:
print("2D Array:\n", arr2)

2D Array:
 [[1 2]
 [3 4]]


In [16]:
print("Transpose:\n", np.transpose(arr2))

Transpose:
 [[1 3]
 [2 4]]


In [17]:
print("Reshaped to (4,1):\n", arr2.reshape(4, 1))

Reshaped to (4,1):
 [[1]
 [2]
 [3]
 [4]]
