In [1]:
import numpy as np


In [2]:
arr = np.array([10, 20, 30, 40, 50])
print("1. Array:", arr)
print("2. Shape:", arr.shape)
print("3. Size:", arr.size)
print("4. Dim:", arr.ndim)
print("5. Dtype:", arr.dtype)
print("6. Max:", np.max(arr))
print("7. Min:", np.min(arr))
print("8. Mean:", np.mean(arr))
print("9. Median:", np.median(arr))
print("10. Std:", np.std(arr))
print("11. Sum:", np.sum(arr))
print("12. CumSum:", np.cumsum(arr))
print("13. Sqrt:", np.sqrt(arr))
print("14. Power 2:", np.power(arr, 2))
print("15. Where >25:", np.where(arr > 25))
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("16. 2D Array:\n", arr2)
print("17. Transpose:\n", np.transpose(arr2))
print("18. Reshape (3x2):\n", arr2.reshape(3, 2))

1. Array: [10 20 30 40 50]
2. Shape: (5,)
3. Size: 5
4. Dim: 1
5. Dtype: int64
6. Max: 50
7. Min: 10
8. Mean: 30.0
9. Median: 30.0
10. Std: 14.142135623730951
11. Sum: 150
12. CumSum: [ 10  30  60 100 150]
13. Sqrt: [3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]
14. Power 2: [ 100  400  900 1600 2500]
15. Where >25: (array([2, 3, 4]),)
16. 2D Array:
 [[1 2 3]
 [4 5 6]]
17. Transpose:
 [[1 4]
 [2 5]
 [3 6]]
18. Reshape (3x2):
 [[1 2]
 [3 4]
 [5 6]]
